#!/bin/bash

# AppArmor enables you restrict the permissions that an application (like your Firefox Browser) has.
# It's your last line of defense against browser-hijacking attacks,
# and enables you to prevent your browser from uploading important files on your Desktop.

# This not a comprehensive list, because my comprehensive version is paranoid and breaks Firefox slightly.
# This is for snap's version of Firefox (the Ubuntu app store).
# Of note, you will no longer be able to upload files from either your desktop or removable media.

iam="$(logname)"    # Let's grab the custom path quick, so we can prevent write access to user.js too
userProfile=$(ls -d /home/$iam/snap/firefox/common/.mozilla/firefox/*.default 2>/dev/null | head -n 1)

path="/etc/apparmor.d/local/snap.firefox.firefox"
#chattr -i "$path"  # Adding immutability toggles is safer, but it would make the script require admin rights.

# Write our modifications using multi-line syntax for easy of management
cat <<EOF_FF > "$path"
# No editing your own rules!
deny $path xw,
deny /var/lib/snapd/apparmor/profiles/snap.firefox.firefox xw,
deny /usr/lib/firefox/distribution/policies.json xw,
deny $userProfile/user.js xw,
#
# Block common exfiltration routes (desktop/removable storage)
deny /home/*/bin/** xrw,
deny /**Desktop** xrw,
deny /**media** xrw,
deny /{,usr/}bin/** xrw,
#
# We really don't want the browser to have sudo, shell access, or lateral movement...
deny /**bash** xrw,
deny /**sudo** xrw,
deny /**mknod** xwr,
deny /**chmod** xwr,
deny /**chattr** xwr,
deny /**su** x,
deny /**sh** x,
deny /**mv** x,
deny /**cp** x,
deny /**py** x,
deny /**ln** x,
deny /**mount** x,
deny /**remount** x,
deny /**umount** x,
#
# Allowing the browser to write to hosts or resolv.conf (DNS) is a disaster waiting to happen.
deny /etc/h[-._+:/]** xrw,
deny /etc/h[0-9]** xrw,
deny /etc/h[^o]** xrw,
deny /etc/ho[^s]** xrw,
deny /etc/hos[^t]** xrw,
deny /etc/host.[^c]** xrw,
deny /etc/host.c[^o]** xrw,
deny /etc/host.co[^n]** xrw,
deny /etc/host.con[^f]** xrw,
deny /etc/host.conf xw,
deny /etc/host.conf*/** xrw,
deny /etc/host.conf?** xrw,
deny /etc/host[-_+:]** xrw,
deny /etc/host[0-9]** xrw,
deny /etc/host[a-m]** xrw,
deny /etc/host[o-r]** xrw,
deny /etc/host[t-z]** xrw,
deny /etc/hostn[^a]** xrw,
deny /etc/hostna[^m]** xrw,
deny /etc/hostnam[^e]** xrw,
deny /etc/hostname xw,
deny /etc/hostname*/** xrw,
deny /etc/hostname?** xrw,
deny /etc/hosts xw,
deny /etc/hosts.[-_+:bc]** xrw,
deny /etc/hosts.[0-9]** xrw,
deny /etc/hosts.[e-z]** xrw,
deny /etc/hosts.a[^l]** xrw,
deny /etc/hosts.al[^l]** xrw,
deny /etc/hosts.all[^o]** xrw,
deny /etc/hosts.allo[^w]** xrw,
deny /etc/hosts.allow xw,
deny /etc/hosts.allow*/** xrw,
deny /etc/hosts.allow?** xrw,
deny /etc/hosts.d[^e]** xrw,
deny /etc/hosts.de[^n]** xrw,
deny /etc/hosts.den[^y]** xrw,
deny /etc/hosts.deny xw,
deny /etc/hosts.deny*/** xrw,
deny /etc/hosts.deny?** xrw,
deny /etc/hosts[^.]** xrw,
deny /etc/r[^e]** xrw,
deny /etc/re[^s]** xrw,
deny /etc/res[^o]** xrw,
deny /etc/reso[^l]** xrw,
deny /etc/resol[^v]** xrw,
deny /etc/resolv.[^c]** xrw,
deny /etc/resolv.c[^o]** xrw,
deny /etc/resolv.co[^n]** xrw,
deny /etc/resolv.con[^f]** xrw,
deny /etc/resolv.conf xw,
deny /etc/resolv.conf*/** xrw,
deny /etc/resolv.conf?** xrw,
deny /etc/resolv[^.]** xrw,
deny /run/systemd/r[^e]** xrw,
deny /run/systemd/re[^s]** xrw,
deny /run/systemd/res[^o]** xrw,
deny /run/systemd/reso[^l]** xrw,
deny /run/systemd/resol[^v]** xrw,
deny /run/systemd/resolv[^e]** xrw,
deny /run/systemd/resolve[^/]** xrw,
deny /run/systemd/resolve/[a-q]** xrw,
deny /run/systemd/resolve/[t-z]** xrw,
deny /run/systemd/resolve/[-._:+/]** xrw,
deny /run/systemd/resolve/[0-9]** xrw,
deny /run/systemd/resolve/r[^e]** xrw,
deny /run/systemd/resolve/re[^s]** xrw,
deny /run/systemd/resolve/res[^o]** xrw,
deny /run/systemd/resolve/reso[^l]** xrw,
deny /run/systemd/resolve/resol[^v]** xrw,
deny /run/systemd/resolve/resolv[^.]** xrw,
deny /run/systemd/resolve/resolv.[^c]** xrw,
deny /run/systemd/resolve/resolv.c[^o]** xrw,
deny /run/systemd/resolve/resolv.co[^n]** xrw,
deny /run/systemd/resolve/resolv.con[^f]** xrw,
deny /run/systemd/resolve/resolv.conf xw,
deny /run/systemd/resolve/resolv.conf?** xrw,
deny /run/systemd/resolve/s[^t]** xrw,
deny /run/systemd/resolve/st[^u]** xrw,
deny /run/systemd/resolve/stub[^-]** xrw,
deny /run/systemd/resolve/stub-[^r]** xrw,
deny /run/systemd/resolve/stub-r[^e]** xrw,
deny /run/systemd/resolve/stub-re[^s]** xrw,
deny /run/systemd/resolve/stub-res[^o]** xrw,
deny /run/systemd/resolve/stub-reso[^l]** xrw,
deny /run/systemd/resolve/stub-resol[^v]** xrw,
deny /run/systemd/resolve/stub-resolv[^.]** xrw,
deny /run/systemd/resolve/stub-resolv.[^c]** xrw,
deny /run/systemd/resolve/stub-resolv.c[^o]** xrw,
deny /run/systemd/resolve/stub-resolv.co[^n]** xrw,
deny /run/systemd/resolve/stub-resolv.con[^f]** xrw,
deny /run/systemd/resolve/stub-resolv.conf** xw,
deny /run/systemd/resolve/stub-resolv.conf?** xrw,
#
# Lock down some toys (like the browser turning the OS off)
deny /usr/lib/snapd/snapctl rw,
deny /usr/lib/snapd/snapctl*/** xw,
deny /usr/lib/snapd/snapctl?** xw,
deny /usr/lib/snapd/system-shutdown xrw,
deny /usr/lib/x86_64-linux-gnu/** x,
deny /usr/lib/x86_64-linux-gnu/**agent** xrw,
deny /usr/lib/x86_64-linux-gnu/**avahi** xrw,
deny /usr/lib/x86_64-linux-gnu/**bash** xrw,
deny /usr/lib/x86_64-linux-gnu/**bind** xrw,
deny /usr/lib/x86_64-linux-gnu/**blkid** xrw,
deny /usr/lib/x86_64-linux-gnu/**bluetooth** xrw,
deny /usr/lib/x86_64-linux-gnu/**bluetooth** xrw,
deny /usr/lib/x86_64-linux-gnu/**boot** xrw,
deny /usr/lib/x86_64-linux-gnu/**bridge** xrw,
deny /usr/lib/x86_64-linux-gnu/**bus** xrw,
deny /usr/lib/x86_64-linux-gnu/**cairo** xrw,
deny /usr/lib/x86_64-linux-gnu/**camera** xrw,
deny /usr/lib/x86_64-linux-gnu/**crypt** xrw,
deny /usr/lib/x86_64-linux-gnu/**cups** xrw,
deny /usr/lib/x86_64-linux-gnu/**curl** xrw,
deny /usr/lib/x86_64-linux-gnu/**data** xrw,
deny /usr/lib/x86_64-linux-gnu/**desktop** xrw,
deny /usr/lib/x86_64-linux-gnu/**dispatch** xrw,
deny /usr/lib/x86_64-linux-gnu/**fwupd** xrw,
deny /usr/lib/x86_64-linux-gnu/**geo** xrw,
deny /usr/lib/x86_64-linux-gnu/**gnome-bg** xrw,
deny /usr/lib/x86_64-linux-gnu/**gnomekb** xrw,
deny /usr/lib/x86_64-linux-gnu/**ip** xrw,
deny /usr/lib/x86_64-linux-gnu/**kbd** xrw,
deny /usr/lib/x86_64-linux-gnu/**lapi** xrw,
deny /usr/lib/x86_64-linux-gnu/**loop** xrw,
deny /usr/lib/x86_64-linux-gnu/**map** xrw,
deny /usr/lib/x86_64-linux-gnu/**mobile** xrw,
deny /usr/lib/x86_64-linux-gnu/**net** xrw,
deny /usr/lib/x86_64-linux-gnu/**net** xrw,
deny /usr/lib/x86_64-linux-gnu/**nvme** xrw,
deny /usr/lib/x86_64-linux-gnu/**photo** xrw,
deny /usr/lib/x86_64-linux-gnu/**pipe** xrw,
deny /usr/lib/x86_64-linux-gnu/**proxy** xrw,
deny /usr/lib/x86_64-linux-gnu/**pulse** xrw,
deny /usr/lib/x86_64-linux-gnu/**py** xrw,
deny /usr/lib/x86_64-linux-gnu/**sambda** xrw,
deny /usr/lib/x86_64-linux-gnu/**sane** xrw,
deny /usr/lib/x86_64-linux-gnu/**sensor** xrw,
deny /usr/lib/x86_64-linux-gnu/**sh** xrw,
deny /usr/lib/x86_64-linux-gnu/**shell** xrw,
deny /usr/lib/x86_64-linux-gnu/**speech** xrw,
deny /usr/lib/x86_64-linux-gnu/**speech** xrw,
deny /usr/lib/x86_64-linux-gnu/**su** xrw,
deny /usr/lib/x86_64-linux-gnu/**trace** xrw,
deny /usr/lib/x86_64-linux-gnu/**tracker** xrw,
deny /usr/lib/x86_64-linux-gnu/**weather** rw,
deny /usr/lib/x86_64-linux-gnu/**wire** xrw,
deny /usr/lib/x86_64-linux-gnu/**fs** xrw,
deny /usr/share/nvidia** xw,
#
# Misc
deny /usr/lib/xorg/** xw,
deny /usr/lib/xorg[^/]** xrw,
deny /usr/share[^/]** xrw,
EOF_FF

# chattr +i "$path"
